### 데이터 정제하기

In [2]:
import pandas as pd

df=pd.read_csv("./data/seoul_park03.csv")
df.head()

,날짜,공휴일,날씨,유료합계,어른,청소년,어린이,외국인,단체,무료합계,총계,연,월,일,요일
0,2016-01-01,O,구름 조금,3359,2799,141.0,419,47,0,1023,4382,2016,1,1,금
1,2016-01-02,O,구름 많음,5173,4370,203.0,600,100,111,2092,7265,2016,1,2,토
2,2016-01-03,O,구름 많음,3008,2571,128.0,309,91,0,1549,4557,2016,1,3,일
3,2016-01-04,X,구름 많음,890,602,NaN,235,51,223,800,1690,2016,1,4,월
4,2016-01-05,X,구름 많음,416,319,35.0,62,43,47,840,1256,2016,1,5,화

### 데이터 정령: sort_values

In [ ]:
# sort_valuse("정렬할 컬럼 이름", 정렬 방법)
# 특정 컬럼의 값을 기준으로 전체 데이터를 정렬한다
df_sorted = df.sort_values("총계", ascending=False) # ascending 생략하면 기본값은 True(오름차순)

df_sorted.head(10)

,날짜,공휴일,날씨,유료합계,어른,청소년,어린이,외국인,단체,무료합계,총계,연,월,일,요일
125,2016-05-05,O,NaN,40219,38511,1708.0,0,476,35,18469,58688,2016,5,5,목
755,2018-05-05,O,맑음,29521,28592,899.0,30,208,65,22789,52310,2018,5,5,토
390,2017-05-05,O,구름 조금,27046,25824,1222.0,0,616,170,19218,46264,2017,5,5,금
156,2016-06-05,O,구름 조금,33504,28943,1079.0,3482,729,190,8239,41743,2016,6,5,일
363,2017-04-08,O,구름 조금,28514,24756,638.0,3120,220,137,12373,40887,2017,4,8,토
378,2017-04-23,O,맑음,25108,21854,269.0,2985,300,333,15008,40116,2017,4,23,일
364,2017-04-09,O,구름 많음,28496,24523,590.0,3383,283,0,10863,39359,2017,4,9,일
157,2016-06-06,O,NaN,31030,26358,1423.0,3249,498,392,8241,39271,2016,6,6,월
413,2017-05-28,O,맑음,28606,25346,675.0,2585,519,4532,10589,39195,2017,5,28,일
92,2016-04-02,O,구름 조금,31407,26605,561.0,3643,169,201,6380,37787,2016,4,2,토
371,2017-04-16,O,구름 많음,27413,23676,383.0,3354,347,37,9706,37119,2017,4,16,일
420,2017-06-04,O,맑음,25815,22617,699.0,2499,469,61,10475,36290,2017,6,4,일
79,2016-03-20,O,구름 조금,27093,22947,535.0,3370,176,0,7267,34360,2016,3,20,일
134,2016-05-14,O,구름 조금,27074,23106,743.0,3225,262,415,6805,33879,2016,5,14,토
155,2016-06-04,O,NaN,26790,23308,727.0,2755,397,389,7012,33802,2016,6,4,토
412,2017-05-27,O,맑음,26602,23575,549.0,2478,398,1314,7193,33795,2017,5,27,토
769,2018-05-19,O,맑음,24047,20837,380.0,2830,110,396,9608,33655,2018,5,19,토
419,2017-06-03,O,맑음,23443,20989,533.0,1921,310,472,9796,33239,2017,6,3,토
100,2016-04-10,O,구름 많음,26912,22441,936.0,3192,446,176,6227,33139,2016,4,10,일
78,2016-03-19,O,구름 조금,26448,22735,422.0,2990,112,178,6683,33131,2016,3,19,토